name: First Worflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    # checkout action
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script # shell script
        run: lsb_release -8